import sqlite3, csv, csvfiles
import os
from app import getdbconnection

#This is a script that generates the map hotspots for the downdectectornav.html file. If any more buildings get added to the database,
#then this code has to be updated. Run the program, and check maphotspotautogen.txt for the autogenerated code. Then, update the html file with this code.

conn = getdbconnection()
buildings = conn.execute('SELECT * FROM Buildings').fetchall()

buildingsData = []
count = 1
for building in buildings:
    buildingsData.append({'name': building['name'], 'xcoord' : building['xcoord'], 'ycoord' : building['ycoord'], 'id' : count})
    count += 1
    
conn.close()

with open('maphotspotautogen.txt', 'w') as f:
    for building in buildingsData:
        aherf = '<area target="" alt="" title="" href="downdetector/' + str(building.get("id")) + '"coords="'+ str(building.get("xcoord")) + ','+ str(building.get("ycoord")) + ',8" shape="circle">\n'
        print(aherf)
        f.write(aherf)

f.close()
